### ISSUE TITLE
create a thumbnail for this viz

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#103]

**Comment by wdwatkins** [comment]
stick with screenshots for now

**Comment by eread-usgs** [comment]
Ok, @wdwatkins that's fine to use screenshot. Is this issue complete? (meaning thumbnail added to repo?)

**Comment by wdwatkins** [comment]
Thumbnail is added, although if there were further data changes it might need to be updated?

**Comment by eread-usgs** [comment]
I think it's probably OK because it will be pretty small.... if major changes occur we can re-make it. Thanks @wdwatkins
