### ISSUE TITLE
Y-Scale on totals histogram.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-VIZLAB/water-use#106]

**Comment by jordansread** [comment]
You want a y-axis?

**Comment by dblodgett-usgs** [comment]
Maybe just a top line number indicating what the max is? I guess we could leave it off since we have the roll over quantities?

**Comment by jordansread** [comment]
My preference is to be as minimal as possible but making sure things make sense. I think we can leave this axis off in the same way we don't have a areal legend for the state sizes.

**Comment by dblodgett-usgs** [comment]
I can dig it.
