### ISSUE TITLE
after new changes deployed, takes a 'refresh' to get app to properly load

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#107]
As shown in this video, I have a consistent issue with the site where, after new changes have been deployed and I do a hard refresh to see those changes, initially no data loads, just the green screen and green bars. I am then required to do an additional refresh to get the data to appear and the app to properly load. I included a gif of what's happening. This has been an issue for me on dev ever since we deployed to dev. 

This is a high priority to be resolved before we release the viz. 

![ezgif com-optimize 1](https://cloud.githubusercontent.com/assets/7794368/20866977/b48e12b8-b9ff-11e6-9688-02bc4a6ee632.gif)

**Comment by eread-usgs** [comment]
Since I made this issue, a PR has been merged so that the default background color is no longer green- so now it may just appear that there is no data showing up, as opposed ot the green layers only showing up.

**Comment by dblodgett-usgs** [comment]
Probably need to minify the Javascript.

**Comment by jiwalker-usgs** [comment]
yeah, we'll need to kill the cache as best we can.

**Comment by jiwalker-usgs** [comment]
need to update to master vizlab to fix this (I'll do this on build box in a bit).

**Comment by eread-usgs** [comment]
verify cache breaker added to vizlab package? @jiwalker-usgs

**Comment by eread-usgs** [comment]
I'm no longer seeing this issue- going to close the it.

**Comment by eread-usgs** [comment]
Seeing this again, but not when I'm in incognito. Not a hugely pressing priority before Tuesday, but still a pretty big deal. @jiwalker-usgs 
![screen shot 2016-12-10 at 2 33 37 pm](https://cloud.githubusercontent.com/assets/7794368/21075992/f241b912-bee5-11e6-9d23-214c7797f08b.png)

**Comment by eread-usgs** [comment]
I'm also seeing this on mobile BTW @jiwalker-usgs. @jread-usgs thought perhaps the SVG was loading but the onload JS was not running

**Comment by jiwalker-usgs** [comment]
This looks good to me, but I wasn't running into the problem very much.  Do others see it as fixed?

**Comment by wdwatkins** [comment]
I haven't been able to make the same problem happen, but after probably 20 + refreshes it did this: 
![image](https://cloud.githubusercontent.com/assets/13987349/21145675/b289ce8c-c114-11e6-8859-62de45e71368.png)

**Comment by wdwatkins** [comment]
@jiwalker-usgs its the same error, now happening in the setTimeout.  Maybe we need a longer delay?

**Comment by jiwalker-usgs** [comment]
I think I properly knocked this one out this morning with @wdwatkins's help.  This is something we should build into the vizlab.js to create a way to determine when the page is really done loading.  Basically the $(document).ready runs before some of the dom is available to work with.
