### ISSUE TITLE
Tooltips for bars don't stay in place on mobile

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#110]
![screenshot_20161204-105821](https://cloud.githubusercontent.com/assets/2349007/20867733/c9a6a8b6-ba10-11e6-8ee5-8ae55bb69dda.png)
This is when you tap a bar and then scroll

**Comment by jiwalker-usgs** [comment]
I don't know that I can get them to stay in place on scroll, but I can probably make them go away.

**Comment by jordansread** [comment]
Is it possible for these tool tips to have the same behavior as the others? I.e., triggered and calculated on mousemove instead of mouseover?

**Comment by jiwalker-usgs** [comment]
It is tricky because we don't have the svg canvas to work on like the other hovers.

**Comment by jiwalker-usgs** [comment]
Is #141 a good enough fix for this?

**Comment by dblodgett-usgs** [comment]
Using the chrome emulator, the tooltips on mobil aren't clearing when you touch something else on the app... They don't move around and basically work, but it seams like they should clear out when you touch something else other than a tool tip?

**Comment by mwernimont** [comment]
Pretty sure JWalks Comment in 141 will fix this issue, PR soonish

**Comment by mwernimont** [comment]
#157 has the tooltip disappear on scroll

**Comment by eread-usgs** [comment]
@jread-usgs are you satisfied with this fix?

**Comment by jiwalker-usgs** [comment]
now #188 is the new tooltips fix, does this act how you'd want?
