### ISSUE TITLE
Any way to link the slider and the bars more accurately?

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#118]
Looks like these are manually set:
![image](https://cloud.githubusercontent.com/assets/2349007/20887318/b633cbb0-babf-11e6-981f-e831c447e607.png)
is slightly offset, and 

![image](https://cloud.githubusercontent.com/assets/2349007/20887327/bd9edd36-babf-11e6-9e02-9e853f8f6ba3.png)
seems closer to centered.

**Comment by mwernimont** [comment]
I'll get to it soon, sometimes the eyes play tricks on me when I've been staring at them all day.

**Comment by dblodgett-usgs** [comment]
This looks OK to me... maybe I'm not seeing it or is it fixed?

**Comment by mwernimont** [comment]
#157
