### ISSUE TITLE
Add analytics events to various things in app

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#123]
Best example so far is in climate-change-walleye-bass viz

**Comment by wdwatkins** [comment]
Thinking events to start: 

 - toggling on/off each use category on the map
 - moving the slider to each timestep
 - which state was moused over, for which period and category
 - which exit links were clicked

**Comment by eread-usgs** [comment]
@wdwatkins how is progress on this one going?

**Comment by wdwatkins** [comment]
should be finished with #156 merged
