### ISSUE TITLE
Add USGS watermark

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#125]
We did this for Hurricane Matthew. Should we do it here? @eread-usgs @dblodgett-usgs perhaps a question for Sonya?

**Comment by eread-usgs** [comment]
I like that and think we should do it again.

**Comment by jordansread** [comment]
@mwernimont I can take this one unless you want it?

**Comment by mwernimont** [comment]
you go for it @jread-usgs
