### ISSUE TITLE
Footer doesn't go to bottom of screen

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/water-use#126]
Maybe intentional? I know I'm weird on my long monitor, but if this is not how we want it to look...the blue bar doesn't go to the bottom of the page:

![image](https://cloud.githubusercontent.com/assets/1105215/20892374/9f9f45fa-bad3-11e6-99d8-af2ad36075fd.png)

**Comment by mwernimont** [comment]
That long monitor man...it doesn't do that on mine, but will see if I can't find something on designing for long monitors since we always have this issue

**Comment by jordansread** [comment]
I think that footer needs some love. E.g., why is the width of the footer div different than the width of the text above it?

**Comment by mwernimont** [comment]
will give it a look

**Comment by mwernimont** [comment]
#127 for the footer widths

**Comment by eread-usgs** [comment]
This appears to be resolved - @ldecicco-USGS is it better on your screen? I am going to move this into the 'footer megathread' if not.

**Comment by mwernimont** [comment]
Theres a potential PR to fix Laura's issue still coming.
