### ISSUE TITLE
Support easy `embed` of this into other apps?

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#129]
I think we called out this being a priority in the past. If so, which part of this should have an easy way to embed it? How would we make that clear to other developers?

**Comment by jiwalker-usgs** [comment]
Would this be embedding only the figure, or the whole content section.  Basically we need to make sure that any embed includes javascript and css.

**Comment by jordansread** [comment]
What would be valuable to others for embed? I think all of this:
![image](https://cloud.githubusercontent.com/assets/2349007/20896532/deb8182e-bae3-11e6-941f-4b6e9c229c59.png)

**Comment by jordansread** [comment]
@jiwalker-usgs what needs to happen to support this?

**Comment by jiwalker-usgs** [comment]
I'm still not clear how the embed will happen.  Is this an iframe with a url, because then we should provide a url without the text and header/footer that people can use in an iframe.  This could just be another publish (page) which leaves out those sections.

**Comment by jiwalker-usgs** [comment]
#188 takes a shot at this, check out embed.html.  We may want a separate CSS file because the main plays around a bit to accomodate the footer.

**Comment by jiwalker-usgs** [comment]
It isn't presented in the viz, but embed.html is available should anyone find the easter egg.  This is another thing we should work into vizlab to make optional for figures/sections.  Part of trick is where our script/css dependencies end up (in page and not section), so automating it is tricky.
