### ISSUE TITLE
New Data QA/QC

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-VIZLAB/water-use#131]
We now have two sources of transcription. We need to flag places the data doesn't match between the initial set we were working with and the new set we are going to use.

**Comment by dblodgett-usgs** [comment]
Got this off to Nancy. I'll leave this issue open pending her review.

**Comment by jordansread** [comment]
@ldecicco-USGS @dblodgett-usgs where are we on this?

**Comment by dblodgett-usgs** [comment]
It is done. Although we don't have a decision on releasing the data yet
