### ISSUE TITLE
Footer issues megathread

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#134]

**Comment by eread-usgs** [comment]
- [x] Don't forget to link to the repo in the footer. I think we somehow missed this on the Hurricane viz - we should link to GH repo by default I would think. w/ a GH logo  
- [x] Get actual titles of visualizations shown associated with thumbnails in footer (e.g. `California Drought Visualized with Open Data` instead of `California drought viz`)
![screen shot 2016-12-05 at 1 37 47 pm](https://cloud.githubusercontent.com/assets/7794368/20899467/244db04a-baf0-11e6-92f9-8d1c14ed073d.png)
- [x] Footer aesthetic

**Comment by mwernimont** [comment]
IE is having issues with the footer images

Not sure why, but writing this to remind myself later

**Comment by jiwalker-usgs** [comment]
Lower CO should be good now, not sure about IE.

**Comment by jordansread** [comment]
@ldecicco-USGS have you looked at the footer on IE lately? is this still an issue?

**Comment by ldecicco-USGS** [comment]
![image](https://cloud.githubusercontent.com/assets/1105215/21062220/6a82d1c6-be15-11e6-89c4-fa1f2b736dbb.png)

**Comment by ldecicco-USGS** [comment]
I think this is the same as in matthew, it's stretching the pictures:

![image](https://cloud.githubusercontent.com/assets/1105215/21062267/a633c0a4-be15-11e6-917c-ab297a4327a1.png)

**Comment by jordansread** [comment]
![image](https://cloud.githubusercontent.com/assets/2349007/21075900/3f8ce5dc-bee3-11e6-8d05-55a2142b3817.png)

**Comment by jordansread** [comment]
@mwernimont see #181

**Comment by jordansread** [comment]
One more thing remaining is to left-justify the two svgs in here. I think @mwernimont is working on that.
