### ISSUE TITLE
Legend- add text to indicate size (area) of states is proportional to state water use 

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#135]
also add a symbol that represents some quantity of area/withdrawals

**Comment by jordansread** [comment]
Anyone have ideas for text in here?
Should be small enough text. @dblodgett-usgs or @eread-usgs ?

**Comment by jordansread** [comment]
Obviously don't have the additional text right, but...
![image](https://cloud.githubusercontent.com/assets/2349007/20900769/27b0b462-baf5-11e6-8419-eebe8ca026b3.png)


(working on getting the number right)
