### ISSUE TITLE
upper penninsula scales on Michigan centroid

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/water-use#151]
The UP scales based on Michigan centroid, so it looks displaced sometimes. Is there anyway to separate so they have individual centroids?

**Comment by jordansread** [comment]
Not without a lot of work. It would involve splitting the two into individual "states", and handling the data appropriately to scale each part the same. Seems like something we could do, but it would be more work than it would seem. Same issue w/ Hawaii and probably a couple of others.

**Comment by lindsayplatt** [comment]
@jread-usgs should we close this as "won't fix"?

**Comment by jordansread** [comment]
IMO, yes.
