### ISSUE TITLE
Response to reviewers

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/water-use#154]
Reviewer 1 comments (MN):

- [x] UNITS should be more clearly stated.  People don't know what "mgd" are.  *Changed as suggested*

- [x] 1st Paragraph - "Mouse over the legend" should say "Click on the legend".  But you CAN mouse over each state to see the value for each state for the time and category selected, should add that.  *Changed as suggested*

- [x] Timeline - If someone goes back to 1950, and have "Total" selected, it would appear that there are no data for 1950, contrary to the title of the website. I think this confusion should be eliminated.  My suggestion (other options may be acceptable): It would be nice to be able to mouse over each year to get some info about what data were collected during that year, or other significant milestones that happened, where there isn't room in the body of the webpage to discuss/show that.  So, for example, if you moused over 1950, you would get something that said "In 1950, only Public Supply and Irrigation data were collected". Or for 1960, "Thermoelectric, and Industrial use categories were added." Etc. (also see suggestion #2) *Good point- here's how we will deal with it- 1) by indicating 'no data' on the timeline for years for which there are no data for any states; and 2) by noting in the text: Prior to 1960, industrial and thermoelectric water use categories were not assessed individually. In progress*

- [x] Instructions/Explanations - I think it needs to be a little more self-explanatory.  To wit: Under the "Water withdrawal categories", put in text that says "click on the category to show data" or something like that.  The two dots for the explanation need a heading, as someone not familiar with this kind of map might not get what they are there for.   *We have added text that clearly instructs users how to interact with the viz in the caption below the map. However, because the map animates upon load, and has interaction without any need to click when users mouse over any part of the viz, we think that users will end up stumbling over the interaction and will discover it themselves.* 

- [ ] ~~Text: 2nd Paragraph - a) Second sentence is repetitive of the first.  b) "This figure shows state-level data, but data at the site, county, and major watershed levels are also being collected wherever possible." --> I believe that county-level data have been collected from the get-go.  This should be mentioned. Then  you can say that data at the site and major watershed levels are being collected when possible.~~ *Won't modify: County level data are not available for the entire record, based on what we understand after working with Molly and Nancy to get the data prepared.*

- [ ] ~~The "USGS" symbol needs to be darker.  Maybe have it change color with the category?~~ *Won't modify: We have purposely included the USGS logo as a watermark and for simplicity of the overall look and feel of the page will not emphasize it more or have it change color.* 

- [ ] ~~Should include an "Other" category for whatever other categories were collected for each time period.  The Year mouse-over (see 1 above)can say which categories are included in "Other" for each time period.~~ *Won't modify: In scoping the viz with Sonya and Molly we decided to keep this to the main 4 categories and not get into the complexity of all of the other categories and sub-categories. Good to consider for future iterations of this, though.*

- [ ] ~~Once this gets approved, it would be very cool to treat each state in the same way.  You could click on the state to move to the state's page.  I'm sure you have all already thought of that!~~*Won't modify: Out of scope for now but we agree that would be cool in future iterations.*

Reviewer 2 comments (NB):

- [x] On the overall visualization concept: I struggled for quite a while figuring out what this was showing me, both on the "what's the story here" level, and a "how's the size of the State being calculated" level.  I think I finally get it, but here's my thought on why I was confused for so long: I kept trying to assign meaning to the relative size of the colored State to its gray outline. So, I would look at a place where the State was completely filled and try to see why that was significant relative to others that were not. I finally decided (and got Dave to confirm) that it's purely the size of the colored State that is conveying information, and it's done by showing an area that is proportional to the water use value. *We have worked to address this issue by 1) reducing the overall amount of text above the map and clearly stating at the top of the map 'State size (area) is proportionate to water withdrawals in million gallons per day, 2) in the caption below the map we go on to further clarify this point, and 3) we moved the legend up above the map to further emphasize it; the legend which indicates how much a relative area (square) is proportional to, for reference.*

- [ ] ~~Get rid of the gray US State map and just present the colored States. You see the State name when you hover, so it's still easy to find the State of interest as long as you're in the right part of the country.~~ *Won't modify: If the grey background was removed, users would have no reference by which to locate states with very small water withdrawals. Those states would look like tiny dots and it would be hard to tell 1) where to mouse over to get more info and 2) which state they are looking at*

- [ ] ~~This also solves another annoyance, where irregularly shaped States, like the Upper Peninsula of Michigan and Long Island, NY, show awkwardly on the gray map when the colored State is small.~~  *Won't modify: We agree that this would be nice to have the Upper and Lower peninsula of Michigan separated when the area changes, but this would take a couple of hours to implement and we judged it to be lower priority than other fixes requested here*

- [x] Change the Explanation colored circle/dot to a square or rectangle--many more States are rectangular-ish than vaguely spherical, so maybe this will help users visually compare the explanation "scale" to various States. *Fixed in #158 and we moved this legend up to above the map to further emphasize it for users* 

- [ ] ~~I do feel that even with these changes, it's hard to get a feel for relative values with the disparate shapes. Example: 1960 Industrial. PA is 4400 Mgal/d, WV next to it is 2300 Mgal/d, OH is 2600 Mgal/d. My eye doesn't see WV and OH as about half of PA.  I do see the 'story' that Industrial steadily shrinks over the years, and Louisiana and Indiana stand out as somewhat counter-trend, but the wildly varying State shapes just have problems when used to show magnitudes of withdrawals. I don't have a fix for this without changing all US State boundaries to make them all rectangular, so I guess we live with it~~  *Won't modify: Having tooltips (mouse overs) expose the data for users to compare, as well as the visual cue of area. There are certainly other ways to do show year by year comparisons for starts, but that is not the main emphasis for this viz.*

- [x] One editorial comment on the visualization: USGS abbreviates million gallons per day as "Mgal/d", not "mgd".  It wins in the NGram viewer, too:
https://books.google.com/ngrams/graph?content=mgd%2CMGD%2CMgal%2Fd&year_start=1900&year_end=2000&corpus=17&smoothing=3&share=&direct_url=t1%3B%2Cmgd%3B%2Cc0%3B.t1%3B%2CMGD%3B%2Cc0%3B.t1%3B%2C%28Mgal%20/%20d%29%3B%2Cc0  *Changed as suggested*

- [x] Lots of editorial comments on the text, so I put it in Word and turned on track changes.   That file is attached. *Most edits have been accepted and applied to the text*

**Comment by jordansread** [comment]
For the USGS symbol comment - I think the symbol is supposed to be a watermark for the map, so it shouldn't stand out, it should instead make sure that the attribution follows re-use of the figure. I don't want to emphasize that on the map because any point of emphasis we put in there takes away from emphasizing the data. However, we could make the watermark the same color as the state backgrounds (right now it looks slightly lighter).

**Comment by dblodgett-usgs** [comment]
If #155 is merged, the checks I added are legit.

**Comment by dblodgett-usgs** [comment]
I'd say the 'Other' category is a won't fix. That would both be a ton of work and could be misleading because of how things have changed over time.

**Comment by eread-usgs** [comment]
@ldecicco-USGS thanks for putting this into an issue.

**Comment by eread-usgs** [comment]
I updated the top comment with Nancy's comments. I think the remaining fixes should be pretty trivial, but text added to the no data state/time combos, and to the overall Instructions/Explanations comment from Martha may need some discussion and thought @jread-usgs looking at you for these ones.

**Comment by eread-usgs** [comment]
@jread-usgs and I are going to take these remaining issues on Friday evening.

**Comment by jordansread** [comment]
Should we just go ahead and change the marker back to a square?

**Comment by eread-usgs** [comment]
sure
