### ISSUE TITLE
IE doesn't support scale transitions

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#159]
is it the use of `scale3d()` or does it also not support `scale`?

- [x] IE fix for states
- [x] IE fix for national bins

**Comment by jordansread** [comment]
The issue here is that the states don't scale. The colors change but the sizes do not.

**Comment by jordansread** [comment]
If IE can't do `scale()` or `scale3d()` with css, we will probably just need to set the `transform="scale(scale)"` directly on the svg element. I don't think we should worry about animating this, just have it abruptly flip.

**Comment by jordansread** [comment]
https://connect.microsoft.com/IE/feedback/details/811744/ie11-bug-with-implementation-of-css-transforms-in-svg
```
IE11 supports SVG transforms through the 'transform' attribute but NOT through the near-identical CSS transform property - unlike all other browsers.

That is annoying, but tolerable.

Unfortunately, IE has convinced itself that it DOES support CSS transforms in SVG. This makes it very difficult to feature-detect. The transform property is present in the style object and both SVGElement.style.transform and SVGElement.style.msTransform return an empty string, implying that support is present.

However setting a CSS transform has no effect on SVG rendering. I am using IE11 on Windows 7 x64 pro.
```

**Comment by jordansread** [comment]
@mwernimont can you put a browser test for IE in 
[this function](https://github.com/USGS-VIZLAB/water-use/blob/master/layout/js/map.js#L39) and [this function](https://github.com/USGS-VIZLAB/water-use/blob/master/layout/js/map.js#L71) so we can slide some code in (like `if (browser === IE){do things}`)?

**Comment by mwernimont** [comment]
@jiwalker-usgs is this a decent solution? http://stackoverflow.com/questions/19999388/check-if-user-is-using-ie-with-jquery

**Comment by mwernimont** [comment]
@jread-usgs #161 Has the global variables

**Comment by ldecicco-USGS** [comment]
OK, closing this issue because we're good enough. Note though, the lower bars *were* actually transitioning just fine. PR#167 made it so the states scale, but they don't have the smooth transition.
