### ISSUE TITLE
IE has trouble with tooltips

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#160]
What we did in hurricane-matthew worked, but here we are having trouble. @ldecicco-USGS can you add details of what you are seeing?

**Comment by ldecicco-USGS** [comment]
When I hover over a state with the developer tools open, I get an error on line 188 of map.js:
```
Object doesn't support property or method 'getAttribute'
```

**Comment by jordansread** [comment]
this is the issue line:
```js
var ref = evt.target.getAttribute('xlink:href').split('-')[0];
```
