### ISSUE TITLE
Call out for why 50-55 thermo and industrial are missing.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-VIZLAB/water-use#163]
Need to add text below the legend when on 1950-55 and the thermoelectric and industrial categories. Should read "Thermoelectric and Industrial categories were not split in 1950 and 1955."

**Comment by dblodgett-usgs** [comment]
If we merge #162 we need to do this.

**Comment by eread-usgs** [comment]
I would recommend that text to read "Prior to 1960, thermoelectric water use was included within the industrial water use category." The word 'split' may be confusing, and doesnt cue the user that those data are actually within industrial. @dblodgett-usgs

**Comment by dblodgett-usgs** [comment]
We aren't showing industrial either. I think your text is better either way though.

**Comment by jordansread** [comment]
Another thing to add here is why HI and AK are showing up as 0 in 1950 instead of no data. Should they be no data?

**Comment by dblodgett-usgs** [comment]
I'll look at that. They should probably be dropped.

**Comment by dblodgett-usgs** [comment]
The HI/AK thing is fixed in #168

**Comment by eread-usgs** [comment]
This is now mentioned in the caption text and is clearly marked on the timeline. I consider it resolved .
