### ISSUE TITLE
Losing hover on bar...sometimes

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/water-use#165]
I'll try to figure out the pattern.

**Comment by ldecicco-USGS** [comment]
First, hover over map, all's good. Click on something anything,, then come back and try hovering over the current year's bar, no hover.

**Comment by wdwatkins** [comment]
Is this that transparent mouse overlay @jread-usgs mentioned in his talk?

**Comment by jiwalker-usgs** [comment]
This is introduced by the mobile fix to hide tooltips at certain points due to (click and scroll).  The tooltip library should maybe be swapped out for something that is less finicky.

**Comment by jordansread** [comment]
@jiwalker-usgs can/should we just replace those bars w/ svg `rect`s? then we can just use the same tip functions. If we set the base of the rectangle relative to 0 in y-space, we can scale y as `scale3d(1, yscale,1)`

like 
```XML
<g transform="translate(200, 100)">
   <rect x="-5" y="-100" height="100" width="10" id="rect-1"/>
   <circle r='2' fill='red'/>
</g>
```
![image](https://cloud.githubusercontent.com/assets/2349007/21034983/8f6405f8-bd81-11e6-8922-e1089d9900c1.png)

scale relative to the baseline (that red dot):
```js
document.getElementById('rect-1').setAttribute('transform','scale(1,0.4)');
```
![image](https://cloud.githubusercontent.com/assets/2349007/21035002/a7013b04-bd81-11e6-8afb-91a6a450239f.png)

**Comment by jiwalker-usgs** [comment]
Yeah, that is probably a good way to go. Can tooltips extend outside of the extent of the svg area?

**Comment by jordansread** [comment]
No, they can't @jiwalker-usgs . Good point. But, I would suggest if we do this we just extend the svg and add the bars on the bottom. Might need to do this anyways if we take on the more complicated solution of #166

**Comment by jiwalker-usgs** [comment]
yeah, makes sense to me

**Comment by jordansread** [comment]
I don't think it makes sense to convert this to svg unless we are doing #166.

**Comment by jordansread** [comment]
@ldecicco-USGS is this bad enough to put the `priority` tag on it?

**Comment by ldecicco-USGS** [comment]
It's a bit weird. But, I think we could release without the fix.

**Comment by jiwalker-usgs** [comment]
#188 should fix

**Comment by lindsayplatt** [comment]
Seems to work for me @jiwalker-usgs !
