### ISSUE TITLE
Make bar graph stacked with categories (?)

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/water-use#166]

**Comment by jordansread** [comment]
![image](https://cloud.githubusercontent.com/assets/2349007/21057065/bab39850-bdfd-11e6-9897-95f5891b1d92.png)

**Comment by lindsayplatt** [comment]
is this still happening?

**Comment by eread-usgs** [comment]
no @lindsaycarr it is not.
