### ISSUE TITLE
Have map and slider div scale relative to the vertical space in the browser/device

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#169]
The map and slider should be maximum size, but limited by the vertical *and* horizontal space. I think it just scaled relative to the width right now. 

for example, here is my browser:
![image](https://cloud.githubusercontent.com/assets/2349007/21053919/1dc54144-bdf1-11e6-90f4-ae44822de27c.png)

I would like this to scale down a bit because it doesn't have space to show the slider and full map in one pane.

**Comment by jordansread** [comment]
@mwernimont can you snag this?

**Comment by mwernimont** [comment]
@jread-usgs #170
