### ISSUE TITLE
Add "no data" or equivalent to missing national totals in bars

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#175]
For thermo and industrial in 1950-1955

![image](https://cloud.githubusercontent.com/assets/2349007/21070961/6a675972-be57-11e6-86a9-dca90aa36acc.png)

We need to do something like this because otherwise it gives the impression that the national totals are 0.

**Comment by jordansread** [comment]
![screenshot_20161210-115932](https://cloud.githubusercontent.com/assets/2349007/21075143/3badfb94-bed0-11e6-8041-3a6086ca9eba.png)

**Comment by eread-usgs** [comment]
Looks good
