### ISSUE TITLE
Add label to timeline bars

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#177]

**Comment by jordansread** [comment]
I am going to start this with `US: {value} Mgal/d` to be consistent w/ the state tool tips. I want to avoid using the word "Total" because that is a category. Other options?

**Comment by dblodgett-usgs** [comment]
Sum: ? Total: {category} {value} ? I think US: is probably good though.

**Comment by eread-usgs** [comment]
I consider this one closed with #180
