### ISSUE TITLE
Get 2015 data in the bars down below

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/water-use#218]

**Comment by ldecicco-USGS** [comment]
OK, so the bars for 2015 are there...they are just on top of 1950:

![image](https://user-images.githubusercontent.com/1105215/39783591-31e4e910-52db-11e8-9f70-4ef68a5be7c9.png)

**Comment by jordansread** [comment]
I think we need to add a css rule for the 2015 bar:
https://github.com/USGS-VIZLAB/water-use/blob/fe777191a7c63b799871e9573e99bec32b55c96e/layout/css/main.css#L138

**Comment by ldecicco-USGS** [comment]
Cool!
