### ISSUE TITLE
DC map scaling

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/water-use#225]
@jread-usgs got any ideas why DC is showing no data on the map? On the hover it's displaying the values right.

![image](https://user-images.githubusercontent.com/1105215/39881844-b537dc74-5447-11e8-9e33-bf9ad8e840a4.png)

**Comment by jordansread** [comment]
Can this get up to dev so I can poke around?

**Comment by ldecicco-USGS** [comment]
S'up on dev:

http://dev-owi.usgs.gov/vizlab/water-use/

The work's on the newData branch:

https://github.com/USGS-VIZLAB/water-use/tree/newData

**Comment by jordansread** [comment]
hmmm...this is what I see on dev: 
![image](https://user-images.githubusercontent.com/2349007/39885975-b3eabaec-5453-11e8-9130-e4843d5434b0.png)

**Comment by ldecicco-USGS** [comment]
Go over to 2005. There is actually a 0 data reported in 2010 and 2015...and I think those 0's are there in the json.

**Comment by jordansread** [comment]
ahh, didn't see the date. I see it, yes

**Comment by jordansread** [comment]
Seems the dev json is repeating itself (http://dev-owi.usgs.gov/vizlab/water-use/js/scaleFactors.json) - there 140 DC fields vs 70 in https://owi.usgs.gov/vizlab/water-use/js/scaleFactors.json

One of the occurrences for each yeah has no field for scaleFactor, so that makes it "missing"

**Comment by ldecicco-USGS** [comment]
Cool, found it I think
