### ISSUE TITLE
header footer

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#32]
copy for hurricane matthew, edit for this viz

**Comment by eread-usgs** [comment]
need thumbnail

**Comment by eread-usgs** [comment]
screenshot from here https://docs.google.com/document/d/170-FKSROa1o8M8H4dPq4eNu84VMnmJKtml-q25bMwXg/edit#

**Comment by lindsayplatt** [comment]
related vizzies:

- CA drought
- CO drought

@jiwalker-usgs since these aren't in the USGS-VIZLAB repository, can we just do the url or should we migrate them? Not sure what kind of effort would be involved in migration.

**Comment by jiwalker-usgs** [comment]
For the footer bit to work they need to be vizlab-ified.  The script looks at the viz.yaml from those repos to get the thumbnail and path.  We could probably put a rush on getting those migrated (I don't think it should be that bad, just a simple viz.yaml with no fetch/process/visualize/publish steps.

**Comment by lindsayplatt** [comment]
can you post the links to the existing repos? I can try to do that.

**Comment by jiwalker-usgs** [comment]
https://github.com/USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis
https://github.com/USGS-CIDA/CIDA-Viz

For now we can even leave them in place and just add viz.yaml and thumbnail (Lower CO already has thumbnail I believe), but if you are daring you can transfer ownership to CIDA-VIZLAB (may want to rename california repo).

**Comment by lindsayplatt** [comment]
need to change viz.yaml >> footer to reflect CO and CA locations + diff repos, but I forgot to branch so now I need to wait for my open PR to get merged before finishing this.

**Comment by jiwalker-usgs** [comment]
We need to deploy CO and CA to include actual thumbnails for the footer.

**Comment by mwernimont** [comment]
IE is having issues with the footer images

**Comment by jiwalker-usgs** [comment]
closing this, #134 can be used for remaining issues.
