### ISSUE TITLE
prototype maps

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#4]
first cut, gifs of 1) total use by state, 2) Irrigation by state

**Comment by wdwatkins** [comment]
Industrial
![industrial](https://cloud.githubusercontent.com/assets/13987349/20775288/cfad6a36-b71f-11e6-9717-da88ca4968cf.gif)
public supply
![publicsupply](https://cloud.githubusercontent.com/assets/13987349/20775289/cfb0e8d2-b71f-11e6-9ca4-03d9af820170.gif)
irrigation
![irrigate](https://cloud.githubusercontent.com/assets/13987349/20775297/d5dd41ec-b71f-11e6-8600-8d23aa45bc24.gif)
Thermoelectric
![thermo](https://cloud.githubusercontent.com/assets/13987349/20775393/4c9c9274-b720-11e6-94c6-53ea461d32d0.gif)

**Comment by wdwatkins** [comment]
**Now with updated data**

Thermoelectric:
![thermo](https://cloud.githubusercontent.com/assets/13987349/20810226/7faeed48-b7ce-11e6-84e9-203c3e46370c.gif)

![industrial](https://cloud.githubusercontent.com/assets/13987349/20810385/21f2d2f4-b7cf-11e6-9703-a521239be665.gif)

![public](https://cloud.githubusercontent.com/assets/13987349/20810586/dcdace1e-b7cf-11e6-9c86-b402099168f2.gif)
![irrigation](https://cloud.githubusercontent.com/assets/13987349/20810701/65c3f660-b7d0-11e6-89b2-f6cee60ad2ce.gif)
