### ISSUE TITLE
social media release plan

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/water-use#48]
https://docs.google.com/document/d/1AwPQdSKqP53fz3Lyz5heWR5KGDDoIAU-2hSUzWd43kU/edit

To do:
- [x] create content
- [x] approve content w/ team
- [x] complete forms for USGS accounts to share these
- [x] make a Gif and send to Scott Horvath

**Comment by lindsaycarr** [comment]
To do:

- [ ] complete forms for USGS accounts to share these

**Comment by lindsayplatt** [comment]
@eread-usgs please review the social media release plan and edit/provide feedback. Lower priority for today, but I would like to submit the forms on Wednesday/Thursday.

**Comment by eread-usgs** [comment]
Hi @lindsaycarr I reviewed the plan, looks great. thank you

**Comment by eread-usgs** [comment]
I would like to label this as priority but don't see how on mobile (and I don't have wifi at the moment.) @lcarr just noting this for you and I'll change it when I get on my laptop

**Comment by wdwatkins** [comment]
Can we/someone tweet this out with an AGU hashtag at some point since @eread-usgs is giving a talk on it?

**Comment by lindsayplatt** [comment]
@eread-usgs what is the title of your talk?

**Comment by wdwatkins** [comment]
Maybe someone/some organization that is involved in the data viz session could tweet/retweet to promote the session?  Maybe a session chair?

**Comment by jordansread** [comment]
@lindsaycarr it is [Maximizing Impact: Pairing interactive web visualizations with traditional print media](https://agu.confex.com/agu/fm16/meetingapp.cgi/Paper/175319)
at noon PT on Thursday (2pm your time)

**Comment by wdwatkins** [comment]
are their size (dimensions or file size) restrictions for twitter gifs?  

edit: looks like 5mb

**Comment by lindsayplatt** [comment]
@wdwatkins this has some additional info: https://dev.twitter.com/rest/media/uploading-media#gifrecs

**Comment by wdwatkins** [comment]
![wateruse](https://cloud.githubusercontent.com/assets/13987349/21109518/0eb3fb9e-c05f-11e6-9dd5-b8a02ef55c77.gif)
this is just under the dimension limit

**Comment by wdwatkins** [comment]
with new data and 10ms less delay
![wu_gif2](https://cloud.githubusercontent.com/assets/13987349/21117358/d58039ee-c07e-11e6-9191-a058d22e69cc.gif)

**Comment by lindsayplatt** [comment]
@wdwatkins from Scott Horvath: 

```
Is it possible to have this graphic redone to either just be wall water supply (blue) or 
to at least pause on the other 4 categories of water supply usage for about 3 seconds 
each? Those last few items flip through so fast I had to watch it at least 5 times to be 
able to read any of the wording and figure out what's what. 

I just want to make sure our followers and those they share it with can see everything.
```
