### ISSUE TITLE
handle no data

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#53]
have a different color and keep full size? Fill w/ hashed lines? AZ is missing some years and we need to deal with that appropriately.

**Comment by wdwatkins** [comment]
Full size with crosshatch seems ok.  Will there be a background map of normal state size that would need to be covered up, so it doesn't just look like it had minuscule water use?

**Comment by jordansread** [comment]
![image](https://cloud.githubusercontent.com/assets/2349007/20850566/6f8003a2-b8a1-11e6-8876-21ba80994dae.png)

here is what it looks like. But AK and AZ have no data here, and both display incorrectly for different reasons.

**Comment by aappling-usgs** [comment]
could also do a graphic '?' in the middle of a state with missing data

**Comment by jordansread** [comment]
![image](https://cloud.githubusercontent.com/assets/2349007/20862585/7e0346b8-b974-11e6-9d1a-897aece928e0.png)

hatching for now?

**Comment by jordansread** [comment]
Looks like we catch some w/ no data, but the json isn't consistent:

![image](https://cloud.githubusercontent.com/assets/2349007/20862625/d8f82d1c-b975-11e6-829e-d8ccfb3b4289.png)
