### ISSUE TITLE
prototype tree diagram

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#6]
Start w fake data if need be. 
MVP: 3/4 categories
++: all categories

**Comment by lindsayplatt** [comment]
the `portfolio` package makes this really easy:

```r
library(portfolio)
data <- read.csv("http://datasets.flowingdata.com/post-data.txt")
mytreemap <- map.market(id=data$id, area=data$views, group=data$category, 
                        color=data$comments, main="FlowingData Map")
```

@jiwalker-usgs @jread-usgs can we svg-ify the `mytreemap` object? If not, we might be able to reverse engineer the algorithms.

**Comment by jordansread** [comment]
maybe? Let me look quick

**Comment by jordansread** [comment]
lots of nesting
```r
names(mytreemap$children$MAP$children$Mapping$children)
 [1] "3485"   "500"    "836"    "4122"   "3581"   "1551"   "4075"   "842"    "3228"   "1062"   "952"    "1293"   "border" "label" 
```

**Comment by jiwalker-usgs** [comment]
I think it is recursive, there is a map inside the map

**Comment by jordansread** [comment]
then I think this is probably what we want in the end:
```r
names(mytreemap$children$MAP$children$Mapping$children$border)
 [1] "x"      "y"      "width"  "height" "just"   "hjust"  "vjust"  "name"   "gp"     "vp"    
```
but I haven't been able to get the geometries yet, because x and y and width etc seem to all be the same for different types. Must be something else going on

actually, looks like the reference may be in the viewpoint (`vp`)

```
unlist(mytreemap$children$MAP$children$`Artistic Visualization`$vp)
                       x                        y                    width                   height           justification1           justification2                   gp.col                  gp.fill 
     "0.349465930446126"      "0.274891826408161"      "0.329947725859565"      "0.214804311711309"                   "left"                 "bottom"                   "blue"            "transparent" 
                  gp.cex                     clip                  xscale1                  xscale2                  yscale1                  yscale2                    angle              valid.just1 
                     "1"                   "TRUE"                      "0"                      "1"                      "0"                      "1"                      "0"                      "0" 
             valid.just2                     name 
                     "0" "Artistic Visualization" 
```
so this is already pretty much an svg

**Comment by lindsayplatt** [comment]
How about this one:

```r
library(treemap)
mymap <- treemap(GNI2014,
        index=c("continent", "iso3"),
        vSize="population",
        vColor="GNI",
        type="value")
```

**Comment by jordansread** [comment]
do you have mock-ups w/ the data in either of these packages?

**Comment by jordansread** [comment]
@lindsaycarr what is the `GNI2014` object from?

**Comment by lindsayplatt** [comment]
the treemap package

**Comment by jordansread** [comment]
```r
library(treemap)
> mymap <- treemap(GNI2014,
+                  index=c("continent", "iso3"),
+                  vSize="population",
+                  vColor="GNI",
+                  type="value")
Error in inherits(dtf, "data.frame") : object 'GNI2014' not found
```
@lindsaycarr ?

**Comment by lindsayplatt** [comment]
hmmm strange - works for me

**Comment by jordansread** [comment]
nevermind, needed to do `data('GNI2014')`

**Comment by lindsayplatt** [comment]
Strange though, I didn't have to do that. 

See #17 - it has my wateruse data treemaps. You can just run this to get them, too:

```r
wateruse_data <- readData('calc-waterData') %>% 
    mutate(category = as.factor(category),
           color = as.numeric(category))

 library(treemap)
  
  yrs_in_data <- sort(unique(wateruse_data$year))
  lapply(yrs_in_data, function(y, wateruse_data){
    wateruse_year <- wateruse_data %>% filter(year == y)
    treemap(wateruse_year, index="category", vSize="value", type="index", title=y)
  }, wateruse_data)
```

**Comment by eread-usgs** [comment]
@jread-usgs or @lindsaycarr can you toss a couple of pngs of the tree maps when you have a moment?

**Comment by lindsayplatt** [comment]
![tm_1950](https://cloud.githubusercontent.com/assets/13220910/20806694/92050f66-b7c1-11e6-9211-cbded4582546.png)
![tm_1955](https://cloud.githubusercontent.com/assets/13220910/20806695/92102fc2-b7c1-11e6-8f44-4ae738a5e8f1.png)
![tm_1960](https://cloud.githubusercontent.com/assets/13220910/20806698/92166644-b7c1-11e6-99e9-91c0674395dc.png)
![tm_1965](https://cloud.githubusercontent.com/assets/13220910/20806696/92123b0a-b7c1-11e6-9235-85f50ed500a6.png)
![tm_1970](https://cloud.githubusercontent.com/assets/13220910/20806697/921503bc-b7c1-11e6-90e5-b293f604f00e.png)
![tm_1975](https://cloud.githubusercontent.com/assets/13220910/20806699/921a2c16-b7c1-11e6-96be-4d8231cd405b.png)
![tm_1980](https://cloud.githubusercontent.com/assets/13220910/20806700/921e2e10-b7c1-11e6-9d3d-d31422a31ea3.png)

**Comment by lindsayplatt** [comment]
![tm_1985](https://cloud.githubusercontent.com/assets/13220910/20806707/983046bc-b7c1-11e6-83a8-bf1c14fba3c7.png)
![tm_1990](https://cloud.githubusercontent.com/assets/13220910/20806708/9831d90a-b7c1-11e6-92f6-9d730cdc0507.png)
![tm_1995](https://cloud.githubusercontent.com/assets/13220910/20806710/98342b7e-b7c1-11e6-93ab-e9c4b1896234.png)
![tm_2000](https://cloud.githubusercontent.com/assets/13220910/20806709/98331374-b7c1-11e6-99e1-d105d69db0ee.png)
![tm_2005](https://cloud.githubusercontent.com/assets/13220910/20806706/98305972-b7c1-11e6-8aa0-aa6037a50bc8.png)

**Comment by lindsayplatt** [comment]
![tm_2010](https://cloud.githubusercontent.com/assets/13220910/20806730/a8aa5320-b7c1-11e6-8768-16d1efe5067f.png)

**Comment by lindsayplatt** [comment]
@eread-usgs some of them don't seem correct, but they do reflect what is in the dataset.

**Comment by lindsayplatt** [comment]
we will need to work on the labels and style (this is all auto), but once we decide what we are moving forward with

**Comment by aappling-usgs** [comment]
cool! looks like we could take out total surface water and total ground water and total surface water, saline and total groundwater, saline, right? because those are sources rather than destinations?

**Comment by aappling-usgs** [comment]
would be awesome if we could eventually get the coloring to reflect similar categories as in the categories table

**Comment by lindsayplatt** [comment]
could be cool for internal communications, but decided not to include in this vizzie
