### ISSUE TITLE
Data Issues

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-VIZLAB/water-use#75]
Use this issue to track other data weirdness you see.

- [x] Montana and Missouri is switched in 1975.
- [x] Thermoelectric has a bar (national total) for 1950, but I thought this category didn't start until later?
- [x] Public Supply *should* have state values for 1950, right? Those are missing
- [x] Total WU per state is missing after 1980
- [x] units on national totals for bars are different than states
- [x] Totals being calculated as zero when some categories are NA.
- [x] Hawaii 1950 irrigation numbers are switched with Georgia? 
- [x] NaNs in a few states from NWISWeb
- [x] Ohio thermoelectric in 2000
- [x] Thermoelectric in '80 - '85 is odd... look at TX, AR, CA.
- [x] DC has a lot of Public Supply pre-1990 (e.g., 218 in 1985), then from 1990 on, mysteriously 0 for all years.

**Comment by dblodgett-usgs** [comment]
Verified the first issue in the report and fixed. Will leave this open for other issues if they come up.

**Comment by jiwalker-usgs** [comment]
related to #82 may want to consolidate the two.

**Comment by jordansread** [comment]
@dblodgett-usgs I updated your bullets ☝️

**Comment by dblodgett-usgs** [comment]
Re: national thermo in 1950, there is a national total for 1950, but the state breakout isn't available. I think we are OK as is? Need to make sure we have a caveat that the national totals are from the 2010 compilation trends and the state data are from individual compilation reports.

**Comment by dblodgett-usgs** [comment]
Unfortunately, the 1950 compilation (by-state) table doesn't have public supply in it. It looks like the data do exist though: http://pubs.usgs.gov/circ/1951/circ115/htdocs/figure3.html The pubs copy of the report doesn't have the appendix with data in it though... will try and track that down.

**Comment by dblodgett-usgs** [comment]
Bars, we are ok having big numbers? I'll make the units adjustment and we'll see what it looks like.

**Comment by dblodgett-usgs** [comment]
I updated the data to fix the hawaii irrigation in 1950. Need to verify that is correct. Have a request in to get all the 1950 report data.

**Comment by dblodgett-usgs** [comment]
I'm also just removing HI from the source data for now, it doesn't exist in 1955 and didn't become a state till 1959, so... probably ok?

**Comment by jordansread** [comment]
I think so - but check that my change from last night still results in it being colored "no data" ? @dblodgett-usgs

**Comment by dblodgett-usgs** [comment]
Yep. It is.

**Comment by dblodgett-usgs** [comment]
Found the fix for 1950 public supply... it's incoming soon.

**Comment by dblodgett-usgs** [comment]
A lot of these issues are fixed in #111.

**Comment by dblodgett-usgs** [comment]
Regarding DC, that's what's in NWIS Web. http://waterdata.usgs.gov/dc/nwis/water_use?format=html_table&rdb_compression=file&wu_area=State+Total&wu_year=ALL&wu_category=PS&wu_category_nms=Public%2BSupply I'll go back to the compilations and get the data.

Actually, the compilations all have 0 too. DC must have switched it's water supply.

**Comment by dblodgett-usgs** [comment]
All of Montana and Missouri were switched in 1975. They were reconciled.

**Comment by dblodgett-usgs** [comment]
Looking at Texas thermoelectric... the data in excel matches the pdf reports. But the reports are strange. Fresh surface water use is 8900, 940, 7460 in 1970, 1980, 1985 and saline is 2800, 5500, 3550 in the same years. Saline goes up in 1980, but not enough to come close to total thermo use from 1975... 

Ahhh... Arkansas has 9700 in 1980 and less than 100 otherwise. Not much I can do since that's what the pdf reports say.

**Comment by dblodgett-usgs** [comment]
Closing this for now. I've started a data review conversation with folks off github.
