### ISSUE TITLE
Need final timeline dates / ranges and titles

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/water-use#81]
![image](https://cloud.githubusercontent.com/assets/2349007/20860588/380dae6a-b941-11e6-8f74-6fb3b42380f1.png)

**Comment by eread-usgs** [comment]
All of the timeline info is placeholder for now- waiting for timeline values from Molly.

**Comment by jiwalker-usgs** [comment]
Also, should this be 2009-present?
