### ISSUE TITLE
Tool tips need data values

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#86]
For tool tips over states and bar plot, need:
1) Name of state (for states not bar chart- bar chart mouseovers should say `US Total` instead of state name)
2) Category (e.g., `Total water withdrawals`, `Industrial water withdrawals` etc)
3) Value (#) and units- volume per year

**Comment by eread-usgs** [comment]
related to #73

**Comment by eread-usgs** [comment]
This is an MVP b/c of the data issues we are having- need to have Molly and our other reviewers be able to see the #s associated w states and totals.

**Comment by eread-usgs** [comment]
@wdwatkins or @lindsaycarr, interested?

**Comment by jordansread** [comment]
I did a partial solution to get the value in, but we still need things like units, maybe a comma (e.g., `1,100`) for the values, and some other text that should be in there. Got the MVP for data review, but not the MVP for release.
