### ISSUE TITLE
when year is selected, should be emphasized over other years. 

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#87]
As it functions now, all years up to the year selected are highlighted. This is somewhat misleading / inconsistent with the data shown on the map, which is only the state totals for a *single* year, not the sum of all years prior. 

Instead, I recommend we have the current year which the slider is on be highlighted in a similar fashion to how the legend category is highlighted / greyed out when selected / not selected.

**Comment by jiwalker-usgs** [comment]
I greyed out the future years to add a bit of flash when moving the time slider, but wasn't sure how to show this most effectively.
