### ISSUE TITLE
consistent colors for text

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#91]
This does not include for text that is purposefully un-bolded, such as for categories that are not currently shown on the legend). Make timeline text and year same color, these should be same color as legend text that @jread-usgs is working on. 

![screen shot 2016-12-03 at 1 07 15 pm](https://cloud.githubusercontent.com/assets/7794368/20861593/83e5da16-b959-11e6-874e-2b4c22b313e0.png)

**Comment by mwernimont** [comment]
@eread-usgs #116

Made the timelslider text and lines black like the legend text.
