### ISSUE TITLE
Add in caption text and title above figure

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#92]
Title / subtitle: `How much water do we use? U.S. water withdrawals, 1950-present` `The USGS National Water-Use Science Project has documented how and where we use water for the last 65 years.`

Caption text: `How and where Americans use water has changed with our population growth and many technological, environmental, and regulatory drivers. In this figure, the area and color of each state polygon show the amount of water withdrawn in that state, either in total (green) or by use category (other colors). Mouse over the legend to see maps for specific water use categories, and slide the time bar left or right to see different years. 
	Every 5 years since 1950, the USGS compiles and estimates water-use information in cooperation with State, Federal, and local agencies to document how the Nation’s water resources are used. Water use data has been collected and compiled by the USGS since 1950 in five year increments. This information is essential to accurately understand how future water demands will be met while maintaining adequate water quality and quantities for human and ecosystem needs. This figure shows state-level data, but data at the site, county, and major watershed levels are also being collected wherever possible. The Water-Use Program hopes to move toward even higher spatial resolution and more frequent reports in the future.`

**Comment by mwernimont** [comment]
@eread-usgs #116

A little worried here with the huge amount of text, we discussed having the map and the slider all visible when you first load the page, and with this text we will probably have to make the map much smaller or the text pretty small to accomplish this. Especially on mobile since it takes about 2-3 scrolls of the default text size to find the map.

**Comment by eread-usgs** [comment]
Text can be out of the range of view if the legend gives some clues to interpretation. Let's discuss when I get into the office. @mwernimont

**Comment by eread-usgs** [comment]
OHHHH I see @mwernimont - I should have said, the caption text (2 paragraphs) can go BELOW the figure.... sorry for writing that wrong.

**Comment by eread-usgs** [comment]
Starting w/ `In this figure`, all text can go below the map

**Comment by mwernimont** [comment]
Now that looks a bit better :)

**Comment by mwernimont** [comment]
@eread-usgs the text you provided is in the viz
