### ISSUE TITLE
Hurricane matthew thumbnail broken

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#94]
![screen shot 2016-12-03 at 3 17 38 pm](https://cloud.githubusercontent.com/assets/7794368/20862254/a5e67ad2-b96b-11e6-93f3-bb615f023f3b.png)

**Comment by lindsayplatt** [comment]
they are actually both broken right now still because we are doing CA & CO. This is still the work that is being finished for #32

**Comment by jordansread** [comment]
So why is the issue closed now?

**Comment by lindsayplatt** [comment]
because #32 is still open and Hurricane-matthew isn't actually one of the thumbnails anymore

**Comment by lindsayplatt** [comment]
I guess I just closed it since this will close just because #32 closes, both can stay open!

**Comment by jordansread** [comment]
gotcha, whoops. Closing
