### ISSUE TITLE
Total water use changes from 2005 to 2010, but no apparent change in areas

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#96]
![screen shot 2016-12-03 at 3 18 48 pm](https://cloud.githubusercontent.com/assets/7794368/20862287/1ae93cde-b96c-11e6-9bd5-3a73137b063a.png)

![screen shot 2016-12-03 at 3 19 00 pm](https://cloud.githubusercontent.com/assets/7794368/20862288/20ee4750-b96c-11e6-8073-8c92150fe416.png)

**Comment by eread-usgs** [comment]
You have to try this on your own computer to see it- I just see no changes in any state areas across these years.... seems strange.

**Comment by jordansread** [comment]
there is no state data for total beyond 1985

**Comment by jordansread** [comment]
LDC is aware and will fix it I think

**Comment by jordansread** [comment]
with #101 you can tell when the dates don't have data.
